# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
# config/packages/fos_ck_editor.yaml
fos_ck_editor:
    configs:
        my_config:
            toolbar: standard
            uiColor: "#cccccc"
            
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
