vich_uploader:
    db_driver: orm

    mappings:
        article_images:
            uri_prefix: /uploads/images/article
            upload_destination: '%kernel.project_dir%/public/uploads/images/article'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    metadata:
        type: attribute
